create table `hakoona-matata-298704.SFCrimeData.tbl_curated_crime`
(
  incident_datetime TIMESTAMP,
incident_date date,
REPORT_DATETIME TIMESTAMP,
ROW_ID STRING,
INCIDENT_ID STRING,
INCIDENT_NUMBER INTEGER,
REPORT_TYPE_CODE STRING,
REPORT_TYPE_DESCRIPTION STRING,
INCIDENT_CODE STRING,
INCIDENT_CATEGORY STRING,
INCIDENT_SUBCATEGORY STRING,
INCIDENT_DESCRIPTION STRING,
RESOLUTION STRING,
POLICE_DISTRICT STRING,
FILED_ONLINE STRING,
CAD_NUMBER INTEGER,
INTERSECTION STRING,
CNN STRING,
ANALYSIS_NEIGHBORHOOD STRING,
SUPERVISOR_DISTRICT STRING,
SUPERVISOR_DISTRICT_2012 STRING,
LATITUDE STRING,
LONGITUDE STRING,
POINT STRING
)
partition by incident_date